language: node_js
notifications:
  email: false
before_script:
- npm ls --production >/dev/null
deploy:
- skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: sZfRSobgiBgO2rGzdzquFaysmJMHjk7GooGLUzV6YnHfOH0ymbMEQc8vHe+eO+vTYFz3PFjO1h6DamQzOGrhhXqdR/OOiMoVcsgwARMKLotD5FHDDCicWOJHokB9DQZgiOFg5UGZmWKZaSoHf6BThP3g/CQTDrXCk19AwCuJDB5SvGlx1FcQ1Ly//frHT439e7hS9KHOwRS2Oji4EM/mrE4pUZ/DXisT3KK/RffZxoUWISJZFgNwqHLcqAM+y3iBYr32yINemANlZKVjPnVDEGYiIygEY4kJJ0li1DxfshhtoMcBm5BOZ6KGMd82y9A7IuX78sc5xhlBOLhnpmlb9xvjWY0hGnKPPPvNeJKnrs0D58WakjreWBx1OxpLVR/cVbFmuiwWVbgQyfQ73gR5ViNYtp5+uKzSoeulJcYAPsaLLk3zBaDL79L5EAg5P6/9AIENn5VgJ8oxge18RVVM99+ZeINRCfsTXWYr5T7cIzgwpQte2TnpSayiXl2P3rJ0iWyVDG6YQUwYsTYtm+ppkSMxtFBtz4OjomhGY3ZoIgbfIsb7P0zs4haHNqlm4Eq9GpySYuVP7Csx2EJfBp0G1iiKY6r6Rw/T98ScRds1w2MLbd0hq9KAeM72WdvdZ7hoKGml8gsHpr6LgZfOrDHITB+j+KTY0af9xNDQebszXIc=
